### ISSUE TITLE
Fill the (sub)modules with detailed content

### ISSUE THREAD

**Issue by vektorious** [ohwmakers/OHM-curriculum#10]
- [x] OHM basics
- [x] 1. Welcome to OHM
- [ ] 2. Staging your project
- [ ] 3. Building open projects
- [ ] 4. OH specifics
- [ ] 5. Roadmapping
- [ ] 6. Licenses and standards
- [ ] 7. Community and communication
- [ ] 8. OHM Outro

**Comment by vektorious** [comment]
I suggest that we work on the curriculum right here in the repository and not in the google doc of the expert review.

@amchagas already worked on the content of:
- Building open projects
- Licenses and standards

which has to be finalized and be transferred into the curriculum (sub)modules

**Comment by vektorious** [comment]
- I added a "work in progress" banner to all modules except "OHM basics" and "Welcome to OHM"
- I adjusted the description of "Staging your project"
- Added the assignments and some more content bullet points for the following (sub)modules
   - Staging your project
   - Building open projects
   - OH specifics
   - Roadmapping

This means the following modules still need some :heart:  
- Licenses and standards
- Community and communication
- OHM Outro

@thessaly

**Comment by amchagas** [comment]
updated licenses and standards as a different branch... PR in a minute

**Comment by amchagas** [comment]
Updated community and communication

**Comment by thessaly** [comment]
OK I reviewed everything, added bullets when missing, made all headers coherent, etc. Work is in https://github.com/ohwmakers/OHM-curriculum/pull/13/

**Comment by vektorious** [comment]
Closing this issue now. We decided to create issues for each submodule to track our progress.
