### ISSUE TITLE
A bug on the homepage

### ISSUE THREAD

**Issue by Plinsboorg** [ohwmakers/OHM-curriculum#26]
The button "Get Started" at the homepage pointing nowhere.
![изображение](https://user-images.githubusercontent.com/42300339/137626033-3fd9a747-123d-4c2f-b88e-2e99366804bc.png)
![изображение](https://user-images.githubusercontent.com/42300339/137626036-07bee02e-c50e-459a-9520-5da2b6d266f4.png)

Web browser Mozilla Firefox 93.0

**Comment by amchagas** [comment]
thanks for the heads up @Plinsboorg!

We are currently finishing review of the curriculum and will fix other issues as well.

**Comment by thessaly** [comment]
I just fixed it (after 3 commits because I'm slower than usual today). The page had been renamed but the link wasn't updated. Thanks for pointing that out!
