### ISSUE TITLE
Review of module "OHM Basics"

### ISSUE THREAD

**Issue by thessaly** [ohwmakers/OHM-curriculum#28]

**Comment by vektorious** [comment]
**Do you agree with the content?**

**Do you agree with the opinions/statements**

**Any content to add/remove?**

**Any more resources?**

**Are the assignments appropriate**

**Typos**

**Comment by thessaly** [comment]
### Do you agree with the content?
Yup, I wrote it XD

### Do you agree with the opinions/statements
Same as above

### Any content to add/remove?
#### "Who is it for"
I suggest moving the section "joining as a mentor or expert" to the home page so it's more visible. 

#### "Our approach"

- I'd change the phrase before the bullet points to: 
> These principles and practices are aligned with the latest work from the open hardware community, and include (but are not limited to):

#### "How does it work"
- The links in the general schedule are broken

#### "Participation guidelines"
- The examples of online community behavior are speaking to forum users, maybe we should adapt them
- NEXT link is broken, should point to "Welcome to OHM"

### Any more resources?
No resources in this section

### Are the assignments appropriate
No assignments in this section

### Typos
Didn't detect any

**Comment by vektorious** [comment]
## Do you agree with the content?
Yes I do :)

## Do you agree with the opinions/statements
Yes :)

## Any content to add/remove?

**"Who is it for"**
I agree to move the section "joining as a mentor or expert" to the home page. However, I'd also keep it in the curriculum as well!
- How about adding something about following NOT as part of the program?

**"Our approach"**
- I agree to Juli for changing the sentence and just did that in PR #38 
- I'd remove the break between the first two sentences.
- Do we have a list of platforms we could link? I'm not sure anymore if we talk about it later.

**"How does it work"**
- Suggestion for later: Update the sketch with our icons.
- in "Content structure" we write that there will be short videos. Are we sure we are doing this?
- fixed links in the table with pull request #38

**"Participation guidelines"**
- I slightly changed the dos and don'ts section with the examples. (see pull request #38)
- I fixed the broken link (see pull request #38)

## Any more resources?
- mb a list of platforms

## Are the assignments appropriate
- there are none

## Typos
- couldn't find a typo
