### ISSUE TITLE
Review of module 1: Welcome to OHM

### ISSUE THREAD

**Issue by thessaly** [ohwmakers/OHM-curriculum#29]

**Comment by thessaly** [comment]
### Do you agree with the content?
Yes

### Do you agree with the opinions/statements
Yes

### Any content to add/remove?
#### 1.1 "Working open"
- "What does working open mean?" last sentence, when it says "an open process", I'd link it to the blog post of the curriculum review

#### 1.2 "The Open Hardware Landscape"
- I'd change the subtitle to "An introduction to open hardware communities"
- I'd add a link to the CERN OHL in the last paragraph of "definitions and licenses"
- I'd add links to Arduino, RepRap and Prusa when mentioned
- Same for GOSH, Hackteria, Appropedia, OpenCores.
- I'd add riscV to that 2nd paragraph in "communities & platforms".
- Link to all platforms Hackaday, Instructables, Hackster, KitSpace

#### 1.3 "Open Hardware Pathways"
- First paragraph: "However, all these projects follow (or should follow) the principles stated by the open hardware definition", I'd link "open hardware definition" to https://www.oshwa.org/definition/
- Change "paperweights" to "biomaterials"
- 2nd paragraph of "diverging pathways", 
> techniques that are closer to **professional** product design
- Link responsible innovation to https://spectrum.ieee.org/what-does-responsible-innovation-mean
- Responsible innovation section needs a closing paragraph

#### 1.4 "Open Hardware Canvas"
- Subtitle: I'd change for "A tool to help you manage your open hardware projects"
- I'd link to the Mozilla Open Canvas and the Lean Canvas. 
- I'd remove the cheeky comment in brackets xD
- Make the github link clickable
- Well, pending example, we can ask open flexure to complete the canvas, or one of Emilio's projects? I thought this was already done...

### Any more resources?
#### For 1.1
We don't have any and no resource comes to my mind right now

#### For 1.2
- Open hardware repository? https://ohwr.org/welcome
- https://search.openknowhow.org/
- GOSH history? https://openhardware.science/about/gosh-history/

#### For 1.3
Maybe we can add good examples of commercial, educational, activist, scientific, artistic open hardware?

#### For 1.4
- Maybe read more about the original business canvas? But not too relevant... https://en.wikipedia.org/wiki/Business_Model_Canvas
- Can't think of any...

### Are the assignments appropriate
#### For 1.1
Yes, I think is good to start with a light exercise as an introduction
#### For 1.2
Yes, but the list of projects from the consultation is missing
#### For 1.3
Yes, still simple but thought-provoking questions
#### For 1.4
Yes, make the link clickable

### Typos 
#### For 1.1
In "What does working open mean?"
-  Sentence: "When you share your process and making ongoing work openly available on the web" --> replace making for make
-   Sentence: "Your project can have positive, transformative effects far beyond what you’re able to imagine" --> replace effects for effect
-   Sentence: "But you should be prepared for the reality that it takes time and energy build a functional community of people who work well together." --> 
replace build for to build
#### For 1.2
Couldn't find any
#### For 1.3
- 3rd paragraph of "diverging pathways": "and works together with scientists to develop a new artefacts adapted to their needs." --> replace with "and works together with scientists to develop new tools adapted to their needs."
- #### For 1.4
Couldn't find any

**Comment by vektorious** [comment]
**NOTE:**
All changes were done in pull request #39

## Do you agree with the content?
Yes

## Do you agree with the opinions/statements
Yes

## Any content to add/remove?
**1.1 "Working open"**
- added a line break after "Hi there, and welcome to the first module of Open Hardware Makers!" 

> "What does working open mean?" last sentence, when it says "an open process", I'd link it to the blog post of the curriculum review
- Do you mean this post? We can add it, but it does not really heave much information about the review process https://openhardware.space/stories/hello_world 


**1.2 "The Open Hardware Landscape"**
> I'd change the subtitle to "An introduction to open hardware communities"
- agree and done
> I'd add a link to the CERN OHL in the last paragraph of "definitions and licenses"
- agree and done
> I'd add links to Arduino, RepRap and Prusa when mentioned
> Same for GOSH, Hackteria, Appropedia, OpenCores.
- agree and done
> I'd add riscV to that 2nd paragraph in "communities & platforms".
- well, doesn't hurt. But can you do it @thessaly 
> Link to all platforms Hackaday, Instructables, Hackster, KitSpace
- agree and done

**1.3 "Open Hardware Pathways"**

> First paragraph: "However, all these projects follow (or should follow) the principles stated by the open hardware definition", I'd link "open hardware definition" to https://www.oshwa.org/definition/
> Change "paperweights" to "biomaterials"
> 2nd paragraph of "diverging pathways", "techniques that are closer to professional product design"
> Link responsible innovation to https://spectrum.ieee.org/what-does-responsible-innovation-mean
- agree and done

> Responsible innovation section needs a closing paragraph
- How about: "Keep these principles in mind when you shape your project, now and in the future."?

**1.4 "Open Hardware Canvas"**
> Subtitle: I'd change for "A tool to help you manage your open hardware projects"
> I'd link to the Mozilla Open Canvas and the Lean Canvas.
- agree and done
> I'd remove the cheeky comment in brackets xD
- I  removed the comment and added the community canvas
> Make the github link clickable
- agree and I did that.

> Well, pending example, we can ask open flexure to complete the canvas, or one of Emilio's projects? I thought this was already done...
- I agree. Let's ask open flexure? 


Any more resources?
**For 1.1**
- No, I removed the Resources 
- 
**For 1.2**
> Open hardware repository? https://ohwr.org/welcome
> https://search.openknowhow.org/
> GOSH history? https://openhardware.science/about/gosh-history/
- agree, added all three
- How about "Open Hardware at CERN"? http://cds.cern.ch/record/2109248/files/CERN-Brochure-2015-002-Eng.pdf

**For 1.3**
> Maybe we can add good examples of commercial, educational, activist, scientific, artistic open hardware?
- I agree, let's collect some.

**For 1.4**
> Maybe read more about the original business canvas? But not too relevant... https://en.wikipedia.org/wiki/Business_Model_Canvas
- I added that

Are the assignments appropriate
For 1.1
> Yes, I think is good to start with a light exercise as an introduction
I agree to that

For 1.2
> Yes, but the list of projects from the consultation is missing

For 1.3
> Yes, still simple but thought-provoking questions
- I agree. I think everything else would be too much

For 1.4
> Yes, make the link clickable
- I think I already did that.

**Comment by vektorious** [comment]
**NOTE:**
All changes were done in pull request #39

## Typos

**For 1.1**
> - Sentence: "When you share your process and making ongoing work openly available on the web" --> replace making for make
> - Sentence: "Your project can have positive, transformative effects far beyond what you’re able to imagine" --> replace effects for effect
> - Sentence: "But you should be prepared for the reality that it takes time and energy build a functional community of people who work well together." -->
> - replace build for to build
- Fixed, didn't find more

**For 1.3**

> - 3rd paragraph of "diverging pathways": "and works together with scientists to develop a new artefacts adapted to their needs." --> replace with "and works together with scientists to develop new tools adapted to their needs."

- Fixed, didn't find more

**Comment by thessaly** [comment]
### 1.1 "Working open"

>Do you mean this post? We can add it, but it does not really heave much information about the review process https://openhardware.space/stories/hello_world

I think we need a proper blogpost on the review process, can do that and link it later on

### 1.2 "The Open Hardware Landscape"

>I'd add riscV to that 2nd paragraph in "communities & platforms".
>> well, doesn't hurt. But can you do it @thessaly

Sure, will add it.

> Responsible innovation section needs a closing paragraph
>> How about: "Keep these principles in mind when you shape your project, now and in the future."?

Sounds good, will add it.

### 1.4 "Open Hardware Canvas"

> Well, pending example, we can ask open flexure to complete the canvas, or one of Emilio's projects? I thought this was already done...
>>  I agree. Let's ask open flexure?

Yes, or @amchagas do you feel like completing the canvas for any of your projects?

### For 1.2, resources:

>    How about "Open Hardware at CERN"? http://cds.cern.ch/record/2109248/files/CERN-Brochure-2015-002-Eng.pdf

Will add that.

### For 1.3, resources:

>    Maybe we can add good examples of commercial, educational, activist, scientific, artistic open hardware?
>>  I agree, let's collect some.

This is pending then.

**Comment by amchagas** [comment]
If Open Flexure peeps can do the Canvas, that would be great, given how well documented and how exemplary their project is!
