### ISSUE TITLE
1.2. The Open Hardware Landscape. Link is missing

### ISSUE THREAD

**Issue by Plinsboorg** [ohwmakers/OHM-curriculum#47]
![image](https://user-images.githubusercontent.com/42300339/152749192-262853b6-debe-40b2-a303-8fd2fbc1c5f3.png)
Link is missing in the Assignment section of the The Open Hardware Landscape page

**Comment by Plinsboorg** [comment]
As I understand it, the list in the Resources section was meant. Is that right?
If so, I believe it would be better to reformulate this sentence into something like:

Take a look at the list in the Resources section.

**Comment by thessaly** [comment]
Thank you @Plinsboorg! The link is now added, it points to an external .md file (https://github.com/ohwmakers/own-resources/blob/main/OSH-good-projects.md)
