### ISSUE TITLE
6.4. Findability standards. Assignment

### ISSUE THREAD

**Issue by Plinsboorg** [ohwmakers/OHM-curriculum#51]
![image](https://user-images.githubusercontent.com/42300339/153581876-71f9a3f2-b170-44f9-9639-61be4cd3d8fa.png)

[these instructions](https://app.standardsrepo.com/MakerNetAlliance/OpenKnowHow/wiki) link is leading to the not existing page

![image](https://user-images.githubusercontent.com/42300339/153582026-05c0ac85-2607-444a-b988-b897f1365b44.png)

**Comment by amchagas** [comment]
Thanks! fixed
