### ISSUE TITLE
Code of conducts

### ISSUE THREAD

**Issue by amchagas** [ohwmakers/OHM-curriculum#7]
Right now we have one "guidelines" file in our main website and a code of conduct in the curriculum repository . We should decide which to keep and/or merge etc...

**Comment by vektorious** [comment]
Well, I think it can be two different things. One is about contributing to the curriculum. The other (guidelines) is for the program itself?

**Comment by amchagas** [comment]
I see. I was just thinking that people should abide by the same set of "rules" no matter which bit of the program they are contributing/participating in? otherwise you can open up the idea that some behaviours are ok in when writing the curriculum, but not when you are chatting with a mentor?

**Comment by vektorious** [comment]
My mistake. You are right. I saw it more as CONTRIBUTING,md and that's definitely different. Code of Conduct/Guidelines should be the same.

**Comment by thessaly** [comment]
+1, we can unify what is in this repo with the CoC in the website

**Comment by vektorious** [comment]
Still a #todo, right?
